version: '3'

services:
  promtail:
    image: docker.io/grafana/promtail:latest
    container_name: promtail
    volumes:
      - /u01/mydev/containers-fs-layout/grafana-promtail/etc/promtail-config.yaml:/etc/promtail/config.yml
      - /u01/mydev/containers-fs-layout/jc21-nginx-proxy-manager/data/logs:/var/log/jc21-nginxpm
      - /u01/mydev/containers-fs-layout/jlesage-nginx-proxy-manager/data/logs:/var/log/jlesage-nginxpm
      - /u01/mydev/containers-fs-layout/soporenet-jc21-nginx-proxy-manager/data/logs:/var/log/soporenet-nginxpm
      - /u01/mydev/containers-fs-layout/nginx/data/logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - mon-net

networks:
  mon-net:
    external:
      name: monitoring-network

